<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
		<script type="text/javascript">
			/*
				Promise 是异步编程的一种解决方案
				Promise对象有以下两个特点:
					1.
						Promise对象代表一个异步操作，有三种状态：
						Pending（进行中）
						Resolved（已完成，又称 Fulfilled）
						Rejected（已失败）
					2.
						一旦状态改变，就不会再变
						Promise对象的状态改变，只有两种可能：从Pending变为Resolved
						和从Pending变为Rejected。只要这两种情况发生，状态就凝固了，
						不会再变了，会一直保持这个结果。如果改变已经发生了，
						你再对Promise对象添加回调函数，也会立即得到这个结果
			*/
			
			 //1.立即执行性
		 		var p = new Promise(function(resolve, reject){
				  console.log("create a promise");
				  resolve("success");
				});
				console.log("after new Promise");
				p.then(function(value){
				  console.log(value);
				});
			 	/*
			 		依次输出
			 		"create a promise"
					"after new Promise"
					"success"
				*/
				
			//2. Promise 三种状态
				var p1 = new Promise(function(resolve,reject){
				  resolve(1);
				});
				var p2 = new Promise(function(resolve,reject){
				  setTimeout(function(){
				    resolve(2);  
				  }, 500);      
				});
				var p3 = new Promise(function(resolve,reject){
				  setTimeout(function(){
				    reject(3);  
				  }, 500);      
				});
				console.log(p1);
				console.log(p2);
				console.log(p3);
				setTimeout(function(){
				  console.log(p2);
				}, 1000);
				setTimeout(function(){
				  console.log(p3);
				}, 1000);
				p1.then(function(value){
				  console.log(value);
				});
				p2.then(function(value){
				  console.log(value);
				});
				p3.catch(function(err){
				  console.log(err);
				});
				/*
			依次输出
			
			初始创建的状态： 
	 		Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: 1}
			Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
			Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
			
			回调函数：
			1
			2
			3
			
			1s后执行的：
			Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: 2}
			Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: 3}
				*/
				
			//3. Promise 状态的不可逆性
				var p1 = new Promise(function(resolve, reject){
				  resolve("success1");
				  resolve("success2");
				});
				var p2 = new Promise(function(resolve, reject){
				  resolve("success");
				  reject("reject");
				});
				p1.then(function(value){
				  console.log(value);
				});
				
				p2.then(function(value){
				  console.log(value);
				});
				/*
					依次输出
					"success1"
					"success" 
					
					Promise状态的一旦变成resolved或rejected时，Promise的状态和值
					就固定下来了，不论你后续再怎么调用resolve或reject方法，
					都不能改变它的状态和值。因此，p1中resolve("success2")并不能将
					p1的值更改为success2，p2中reject("reject")也不能将p2的
					状态由resolved改变为rejected.
				*/
				
			//4.链式调用
				var p = new Promise(function(resolve, reject){
				  resolve(1);
				});
				p.then(function(value){               //第一个then
				  console.log(value);
				  return value*2;
				}).then(function(value){              //第二个then
				  console.log(value);
				}).then(function(value){              //第三个then
				  console.log(value);
				  return Promise.resolve('resolve'); 
				}).then(function(value){              //第四个then
				  console.log(value);
				  return Promise.reject('reject');
				}).then(function(value){              //第五个then
				  console.log('resolve: '+ value);
				}, function(err){
				  console.log('reject: ' + err);
				})
				/*
					依次输出
					1
					2
					undefined
					"resolve"
					"reject: reject" 
					
					代码中第一个then会返回一个值为2（1*2），状态为resolved的Promise
					对象，于是第二个then输出的值是2。第二个then中没有返回值，因此将
					返回默认的undefined，于是在第三个then中输出undefined。
					第三个then和第四个then中分别返回一个状态是resolved的Promise
					和一个状态是rejected的Promise，依次由第四个then中成功的回调函数
					和第五个then中失败的回调函数处理。
				*/
				
			//5. Promise then() 回调异步性
				var p = new Promise(function(resolve, reject){
				  resolve("success");
				});
				p.then(function(value){
				  console.log(value);
				});
				console.log("which one is called first ?");
				/*
					依次输出：
					"which one is called first ?"
					"success"
					
					Promise接收的函数参数是同步执行的，但then方法中的回调函数执行
					则是异步的，因此，"success"会在后面输出。
				*/
			
			//6. Promise 中的异常
				var p1 = new Promise( function(resolve,reject){
				  foo.bar();
				  resolve( 1 );      
				});
				p1.then(
				  function(value){
				    console.log('p1 then value: ' + value);
				  },
				  function(err){
				    console.log('p1 then err: ' + err);
				  }
				).then(
				  function(value){
				    console.log('p1 then then value: '+value);
				  },
				  function(err){
				    console.log('p1 then then err: ' + err);
				  }
				);
				var p2 = new Promise(function(resolve,reject){
				  resolve( 2 );    
				});
				p2.then(
				  function(value){
				    console.log('p2 then value: ' + value);
				    foo.bar();
				  }, 
				  function(err){
				    console.log('p2 then err: ' + err);
				  }
				).then(
				  function(value){
				    console.log('p2 then then value: ' + value);
				  },
				  function(err){
				    console.log('p2 then then err: ' + err);
				    return 1;
				  }
				).then(
				  function(value){
				    console.log('p2 then then then value: ' + value);
				  },
				  function(err){
				    console.log('p2 then then then err: ' + err);
				  }
				);
				/*
					依次输出
					p1 then err: ReferenceError: foo is not defined
					p2 then value: 2
					p1 then then value: undefined
					p2 then then err: ReferenceError: foo is not defined
					p2 then then then value: 1
					
					Promise中的异常由then参数中第二个回调函数
					（Promise执行失败的回调）处理，异常信息将作为Promise的值。
					异常一旦得到处理，then返回的后续Promise对象将恢复正常，
					并会被Promise执行成功的回调函数处理。
					另外，需要注意p1、p2 多级then的回调函数是交替执行的 ，
					这正是由Promise then回调的异步性决定的。
				*/
				
			//7. Promise.resolve()
				var p1 = Promise.resolve( 1 );
				var p2 = Promise.resolve( p1 );
				var p3 = new Promise(function(resolve, reject){
				  resolve(1);
				});
				var p4 = new Promise(function(resolve, reject){
				  resolve(p1);
				});
				
				console.log(p1 === p2); 
				console.log(p1 === p3);
				console.log(p1 === p4);
				console.log(p3 === p4);
				
				p4.then(function(value){
				  console.log('p4=' + value);
				});
				
				p2.then(function(value){
				  console.log('p2=' + value);
				})
				
				p1.then(function(value){
				  console.log('p1=' + value);
				})
				/*
					依次输出
					true
					false
					false
					false
					p2=1
					p1=1
					p4=1
					
					Promise.resolve(...)可以接收一个值或者是一个Promise对象
					作为参数。当参数是普通值时，它返回一个resolved状态的Promise
					对象，对象的值就是这个参数；当参数是一个Promise对象时，
					它直接返回这个Promise参数。因此，p1 === p2。但通过new的方式
					创建的Promise对象都是一个新的对象，因此后面的三个比较结果
					都是false。另外，为什么p4的then最先调用，但在控制台上是
					最后输出结果的呢？因为p4的resolve中接收的参数是一个
					Promise对象p1，resolve会对p1"拆箱"，获取p1的状态和值，
					但这个过程是异步的。
				*/
				
			//8. resolve vs reject
				var p1 = new Promise(function(resolve, reject){
				  resolve(Promise.resolve('resolve'));
				});
				var p2 = new Promise(function(resolve, reject){
				  resolve(Promise.reject('reject'));
				});
				var p3 = new Promise(function(resolve, reject){
				  reject(Promise.resolve('resolve'));
				});
				p1.then(
				  function fulfilled(value){
				    console.log('fulfilled: ' + value);
				  }, 
				  function rejected(err){
				    console.log('rejected: ' + err);
				  }
				);
				p2.then(
				  function fulfilled(value){
				    console.log('fulfilled: ' + value);
				  }, 
				  function rejected(err){
				    console.log('rejected: ' + err);
				  }
				);
				p3.then(
				  function fulfilled(value){
				    console.log('fulfilled: ' + value);
				  }, 
				  function rejected(err){
				    console.log('rejected: ' + err);
				  }
				);
				/*
					依次输出
					p3 rejected: [object Promise]
					p1 fulfilled: resolve
					p2 rejected: reject
					
					Promise回调函数中的第一个参数resolve，会对Promise执行"拆箱"
					动作。即当resolve的参数是一个Promise对象时，resolve会"拆箱"
					获取这个Promise对象的状态和值，但这个过程是异步的。
					p1"拆箱"后，获取到Promise对象的状态是resolved，因此
					fulfilled回调被执行；p2"拆箱"后，获取到Promise对象的
					状态是rejected，因此rejected回调被执行。但Promise回调函数中的
					第二个参数reject不具备"拆箱"的能力，reject的参数会直接传递给
					then方法中的rejected回调。因此，即使p3 reject接收了
					一个resolved状态的Promise，then方法中被调用的依然是rejected，
					并且参数就是reject接收到的Promise对象。
				*/
		</script>
	</body>
</html>
